### ISSUE TITLE
Svg

### ISSUE THREAD

**Issue by RALMAZ** [RALMAZ/ralmaz.github.io#5]
```html
<div id='wrapper'>
  <svg viewBox='10 200 100 100' preserveAspectRatio='xMidYMid meet'>
    <path id='diamondOutline' d='m 26.010416,241.4758 15.640199,-15.65113 h 8.628486 l -8.628486,15.65113 h 30.659157 l -9.243353,-15.65113 h 9.243353 L 87.791355,241.4758 H 72.309772 L 56.908088,272.35906 41.650615,241.4758 Z M 56.908088,272.35906 26.010416,241.4758 h 15.640199 l 8.628486,-15.65113 h 12.787318 l 9.243353,15.65113 15.469891,0.0117 -30.878777,30.87879 15.408886,-30.89049 H 41.650615 Z'/>
  </svg>
</div>
```

```css
#wrapper {
  width:95vw;
  height:90vh;
  background-color:rgb(175,175,175);
}
svg {
  width:100%;
  height:100%;
  border:rgba(125,125,125,1) solid 3px;
}
#diamondOutline {
  fill:none;
  /*STROKE ANIMATION PROP HERE*/
  animation: diamondStrokeRepaint 4s linear infinite;
  -webkit-animation: diamondStrokeRepaint 4s linear infinite;
  /*STROKE ANIMATION PROP HERE*/
  stroke-width:2;
  stroke-linecap:butt;
  stroke-linejoin:round;
}

/*STROKE ANIMATION KEYFRAMES HERE*/
@keyframes diamondStrokeRepaint {
  0%,100% {stroke:#C861AE;}
  20% {stroke:#64359E;}
  50% {stroke:#64359E;}
  70% {stroke:#64359E;}
}
/*STROKE ANIMATION KEYFRAMES HERE*/

```
